<!doctype html>  


<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Garagistry : My Vehicles</title>
  <meta name="description" content="Meta description of the rendered page">

  <!--  Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

<!--[if lt IE 8]>
  <link rel="stylesheet" href="/css/blueprint/ie.css" type="text/css" media="screen, projection">
<![endif]-->

  <!-- Blueprint Grid -->
  <link rel="stylesheet" href="/css/bb/grid.css" type="text/css" /> 
  
  <!-- Garagistry CSS -->
  <link rel="stylesheet" href="/css/style.css?v=4">
    
  <!-- 3rd party lib CSS -->
  <link rel="stylesheet" href="/js/mylibs/prettyphoto/css/prettyPhoto.css">
  <link rel="stylesheet" href="/css/jquery.gritter.css" />
  <link rel="stylesheet" href="/css/chosen.css" />
  <link rel="stylesheet" href="/css/colorbox.css" />
  
  <!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -->
  <script src="/js/libs/modernizr-2.0.6.min.js"></script>
  <script type="text/javascript" src="http://use.typekit.com/scv2ytb.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body class="">

	<div id="container" class="container">
		<header>
		<!-- Logo -->
			<div class="span-12">
				<h1><a href="/"><img src="/images/logo.png" alt="Garagistry" id="logo" width="256" height="47" /></a></h1>
			</div>
			<!-- Secondary Navigation -->
			<div class="span-12 last">
				<ul id="admin-nav">
					<li><b>Demo Man</b></li>
					<li><a href="/account/">My Account</a></li>	
					<li><a href="/account/logout/">Sign Out</a></li>
					<li class="last"><a href="/help/">Help</a></li>
				</ul> <!-- /#admin-nav -->				
			</div>
		</header>
	<!-- Nav -->
	<nav>
		<div class="span-24">
			<div id="main-nav">
				<div class="my-garagistry">
					<div class="span-24">
						<ul>
							<li id="nav-mygaragistry" class="span-6"><a href="#">My GARAGISTRY</a></li>
							<li id="nav-explore" class="span-4"><a href="#">EXPLORE</a></li>
							<li id="nav-qa" class="span-4"><a href="#">Q <span class="amp">&amp;</span> A</a></li>
							<li id="nav-news" class="span-5"><a href="#">NEWS <span class="amp">&amp;</span> EVENTS</a></li>
							<li id="nav-resources" class="span-3 append-2 last"><a href="#">RESOURCES</a></li>
						</ul> <!-- /#main-nav -->
					</div>
					<div class="clear" />
					<div class="span-17">
						<ul id="sub-nav">
							<li><a href="/">Overview</a></li>
							<li class="active"><a href="/">Vehicles</a></li>
							<li><a href="/">Journal</a></li>
							<li><a href="#">Favorites</a></li>
							<li class="last"><a href="#">Badges</a></li>
						</ul> <!-- /#sub-nav -->
					</div>
					<!-- Search -->
					<div class="span-7 last">
						<form action="/search/" method="get" id="search-form">
							<fieldset>
								<input type="text" name="q" value="" />
								<input type="reset" value="">
								<input type="hidden" value="Go" />
							</fieldset>
						</form>
					</div> <!-- #span-7 last -->
				</div> <!-- /.my-garagistry -->
			</div> <!-- /#main-nav -->
		</div> <!-- /.span-24 -->
		<div class="clear"></div>
	</nav>
	
	<!-- Main Content -->
	<div id="main-content">
		<div class="span-24">
			<div class="box span-24">
			<?php echo $this->layout()->content ?>
			</div> <!-- /.box -->
		</div> <!-- /#span-24-->
	</div>
	
	<footer>
	<div id="footer" class="span-12">
	<div id="footer" class="span-4">
	<ul>
	<li><a href="/">Home</a></li>
	<li><a href="/about/story/">Our Story</a></li>
	<li><a href="/dummy/blog/">Blog</a></li>
	</ul>
	</div>
	<div id="footer" class="span-8 last">
	<ul>
	<li><a href="/about/terms/">User Agreement</a></li>
	<li><a href="/about/privacy/">Privacy Policy</a></li>
	<li><a href="/about/contact/">Contact Us</a></li>
	</ul>
	</div>
	</div>
	
	<div id="footer" class="span-12 last">
	<p id="tagline">Preserving Automotive History&hellip;One Car at a Time&trade;</p>
	<p id="copyright">&copy;2011 Garagistry, LLC. All rights reserved</p>
	</div>
	</footer>
	</div> <!-- /#container -->


  <!-- Javascript at the bottom for faster page loading -->

  <!-- Grab Google CDN's jQuery. fall back to local if necessary -->
  <!--  Google api...which is better, direct or via google.load?
  <script type="text/javascript" src="http://www.google.com/jsapi"></script>
  <script type="text/javascript">google.load('jquery', '1.6.2');</script> -->        
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.js"></script>
  <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.6.2.min.js"><\/script>')</script>
  
 
  <!-- scripts concatenated and minified via ant build script-->
  <script src="/js/plugins.js"></script>
  <script src="/js/mylibs/prettyphoto/js/jquery.prettyPhoto.js"></script>
  <script src="/js/script.js"></script>
  <!-- end build scripts-->

  <script src="/js/libs/jquery-ui-1.8.10.custom.min.js" type="text/javascript"></script>
  <script src="/js/libs/jquery.gritter.js" type="text/javascript"></script>
  <script src="/js/libs/jquery.qtip.min.js" type="text/javascript"></script>
  <script src="/js/libs/jquery.maskedinput.js" type="text/javascript"></script>
  <script src="/js/libs/jquery.form.js" type="text/javascript"></script>
  <script src="/js/libs/bbq.js" type="text/javascript"></script>
  <script src="/js/mylibs/jquery.django.validation.js" type="text/javascript"></script>
  <script src="/js/libs/jquery.colorbox-min.js" type="text/javascript"></script>
  <script src="/js/libs/chosen/chosen.jquery.min.js" type="text/javascript"></script>

  

  

  <script type="text/javascript">
    $(function(){
        /* Search Bar active/inactive states */
        $('#main-nav input[type=text]').focus(function() {
            $(this).toggleClass('active');
            $('#main-nav input[type=reset]').toggleClass('active');
        }).blur(function() {
            $(this).toggleClass('active');
            $('#main-nav input[type=reset]').toggleClass('active');
        });
        
    });

    $(function() {
        $('#id_build_date').datepicker();
        $('#id_purchase_date').datepicker();

        /* Enable any chosen select fields */
        $('.chzn-select').chosen({no_results_text: 'No results matched'});
    });

    $(function() {
        $('.vehicle-profile').hover(
            function(){
                $(this).find('.vehicle-edit').toggle();
                $(this).find('.vehicle-title a').toggleClass('active');
            }
         );
    });

	$(document).ready(function(){
	
		//Hide (Collapse) the toggle containers on load
		$(".hidden").hide(); 
	
		//Switch the "Open" and "Close" state per click then slide up/down (depending on open/close state)
		$("h2.trigger").click(function(){
			$(this).toggleClass("active").next().slideToggle("slow");
			return false; //Prevent the browser jump to the link anchor
		});
	
	});

        $(function(){
            // Custom radio inputs
            $('input').customInput();
            
            // find all "other" inputs and hide the ones that are empty
            $("#vehicle_specs .other input").each(function() {
                if (this.value == '') {
                    $(this).parent().hide();
                }
            });

            $("#vehicle_specs span.form-field select").change(function() {
                other_id = '#' + this.id.substring(3) + '_other';
                other = $(other_id);
                if (this.value == 'other') {
                    if ($(other).is(':hidden')) {
                        $(other).show();
                    }
                }
                else {
                    $(other).hide(); //slideUp("slow");
                }
            });
        });

        function copySpecs(name) {
          var fact = '#id_fact_' + name;
          var curr = '#id_curr_' + name;
          var fact_other = 'input#id_fact_' + name + '_other';
          var curr_other = 'input#id_curr_' + name + '_other';
          fact_value = $(fact).val();
          other_value = $(fact_other).val()
          $(curr).val(fact_value);
          $(curr_other).val(other_value);
          $(curr).trigger("liszt:updated");  // notify Chosen
          $(curr).trigger("change");         // notify plain select widget
        };

        // AJAX validation
        $('#vehicle_specs').validate('/vehicles/xhr/validate-specs/',
            {type: 'div',
            fields: ['mileage', 'fact_displacement', 'curr_displacement'],
            event: 'change'
            }
         );

			jQuery(document).ready(function($) {
		    
		    //qTips Jquery plugin creates custom tooltips on click or hover. http://craigsworks.com/projects/qtip2/
		    // Create the tooltips only on document load
			$(document).ready(function() {
			   // Make sure to only match links with the .reference class and 
			   $('.reference[rel]').each(function()
			   {
			      // We make use of the .each() loop to gain access to each element via the "this" keyword...
			      $(this).qtip(
			      {
			         content: {
			            // Set the text to an image HTML string with the correct src URL to the loading image you want to use
			            text: '<img class="throbber" src="/projects/qtip/images/throbber.gif" alt="Loading..." />',
			            ajax: {
			               url: $(this).attr('rel') // Use the rel attribute of each element for the url to load
			            },
			           
			         },
			         position: {
			            at: 'top center', // Position the tooltip above the link
			            my: 'bottom center',
			            viewport: $(window), // Keep the tooltip on-screen at all times
			            adjust: {
					         x: 0, y: -10
					      },
			            effect: false // Disable positioning animation
		
			         },
		
					 show: {
					 	event: 'click'
					 },
			         hide: {
			         	event: 'click unfocus'
			         },
			         width:false,
			         height:false,
			         style: {
			            classes: 'ui-tooltip-rounded ui-tooltip-shadow  ui-tooltip-garagistry no-point'
			         }
			        
			      })
			      $(this).click( function() {
			      	$(this).toggleClass("focussed");
			     	}
			      );
				  $(this).focusout( function() {
			      	$(this).removeClass("focussed");
			     	}
			      );
			     
			   })
		
			   // Make sure it doesn't follow the link when we click it
			   .click(function(event) { event.preventDefault(); });
			  });
		    });
		    $(document).ready(function(){
				//Examples of how to assign the ColorBox event to elements
				$("a.photo-link").colorbox();
				$("a.add-photo").colorbox();

			});
		</script>
  
  <!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
   var _gaq = [['_setAccount', 'UA-25799072-1'], ['_setDomainName', 'garagistry.com'], ['_trackPageview']];
   (function(d,t){var g = d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>


  
</body>
</html>