<div id="vehicle-list-header">
	<a href="/vehicles/demo/add/"><div id="vehicle-add" class="gbutton">Add a Vehicle</div></a>
	<div class="paperclipped"></div>
	<h1>My VEHICLES</h1>
</div>
<div id="vehicles-vehicle" class="vehicle-profile">
	<div class="vehicle-edit"><a href="/vehicles/demo/1959-chevrolet-bel-air-1/edit/">Edit <img src="/images/icons/edit_trans.png"/></a></div>
	<div class="vehicle-photo-stack">
		<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air2_profile.jpg" class="top-photo" alt="The Bel Air" title="" width="170" height="180" />
		<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air4_profile.jpg" class="bottom-photo" alt="My favorite" title="" width="170" height="180" />
	</div>
	<div class="vehicle-summary">
		<div class="vehicle-title">
			<a href="/vehicles/demo/1959-chevrolet-bel-air-1/">1959 Chevrolet Bel Air</a>
		</div>
		<div class="vehicle-summary-details">
			<dl>
				<dt>VIN</dt>
				<dd></dd>
			</dl>
			<dl>
				<dt>SPECS</dt>
				<dd>350 ci V-8</dd>
			</dl>
			<dl>
				<dt>CATEGORY</dt>
				<dd>Classic</dd>
			</dl> 
			<dl class="favorites">
				<dt>FAVORITES</dt>
				<dd><img src="/images/icons/favstar_on.png" width="19" height="18"/> 4</dd>
			</dl>
		</div>
		<div class="profile-completion">
			<span class="completion-percentage">NEEDED: transmission type, transmission speeds...</span>   PROFILE COMPLETION: 35% <div class="completion-bar"><span style="width: 35%"></span></div>
		</div>
	</div>
</div>

<div id="vehicles-vehicle" class="vehicle-profile">            
	<div class="vehicle-edit"><a href="/edit/">Edit <img src="/images/icons/edit_trans.png"/></a></div>
	<div class="vehicle-photo-stack">
		<img src="/media/photo_cache/demo/__fiat_500_profile.jpg" class="bottom-photo" alt="The little car that could..." title="" width="170" height="180"  />
	</div>
	<div class="vehicle-summary">
		<div class="vehicle-title">
			<a href="/vehicles/demo/1955-fiat-500-1/">1955 Fiat 500</a>
		</div>
		<div class="vehicle-summary-details">
			<dl>
				<dt>VIN</dt>
				<dd></dd>
			</dl>
			<dl>
				<dt>SPECS</dt>
				<dd>1500 cc Inline 4, 3 Speed Manual</dd>
			</dl>
			<dl>
				<dt>CATEGORY</dt>
				<dd>Classic</dd>
			</dl> 
			<dl class="favorites">
				<dt>FAVORITES</dt>
				<dd><img src="/images/icons/favstar_on.png" width="19" height="18"/> 16</dd>
			</dl>
		</div>
		<div class="profile-completion">
			<span class="completion-percentage">NEEDED: interior color</span> PROFILE COMPLETION: 90% <div class="completion-bar"><span style="width: 90%"></span></div>
		</div>
	</div>
</div>
<div id="vehicles-vehicle" class="vehicle-profile">            
	<div class="vehicle-edit"><a href="/vehicles/demo/1933-buick-model-90-2/edit/">Edit <img src="/images/icons/edit_trans.png"/></a></div>
	<div class="vehicle-photo-stack">
		<img src="/media/photo_cache/demo/__1934_buick_90_profile.jpg" class="top-photo" alt="The Ol&#39; Model 90" title="" width="170" height="180"/>
		<img src="/media/photo_cache/demo/DSCN5704_profile.jpg" class="bottom-photo" alt="Trim Tag" title="" width="170" height="180"/>     
	</div>
	<div class="vehicle-summary">
		<div class="vehicle-title">
			<a href="/vehicles/demo/1933-buick-model-90-2/">1933 Buick Model 90</a>
		</div>
		<div class="vehicle-summary-details">
			<dl>
				<dt>VIN</dt>
				<dd></dd>
			</dl>
			<dl>
				<dt>SPECS</dt>
				<dd>(no specs)</dd>
			</dl>
			<dl>
				<dt>CATEGORY</dt>
				<dd>Antique</dd>
			</dl> 
			<dl class="favorites">
				<dt>FAVORITES</dt>
				<dd><img src="/images/icons/favstar_on.png" width="19" height="18"/> 18</dd>
			</dl>
		</div>
		<div class="profile-completion">
			<span class="completion-percentage">NEEDED: cylinders, displacement...</span>PROFILE COMPLETION: 20% <div class="completion-bar"><span style="width: 20%"></span></div>					</div>
	</div>
</div>
<div class="pagination">
	<span class="current page">1</span>
	<a href="?page=2" class="page">2</a>
	<a href="?page=3" class="page">3</a>
	<span class="prev">&hellip;</span>
	<a href="?page=2" class="next">Next</a>
	<a href="?page=3" class="last">Last</a>
</div> <!-- /.pagination -->	