<div id="vehicle-edit-head" class="vehicle">
	<div id="vehicle-rvt">
		<img src="/images/rvt_sample-100.png" width="100" height="57" />
	</div>
	<div class="vehicle-photo">
		<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air2_profile.jpg" alt="The Bel Air" title="" />
	</div>
	<div id="vehicle-title">
		<div id="vehicle-year">1959</div>
		<div id="vehicle-make">Chevrolet</div>
		<div id="vehicle-model">Bel Air</div>
	</div>
	<div class="profile-completion">
		<span class="completion-percentage">NEEDED: transmission type, transmission speeds...</span> PROFILE COMPLETION: 35%
		<div class="completion-bar"><span style="width: 35%"></span></div>
	</div>
	<!-- /.profile-completion -->
</div>
<div id="vehicle-edit-nav">
	<ul>
		<li id="specs"><a href="/edit">Vehicle Specs</a></li>
		<li id="trim"><a href="/edit/trim/">Trim Level</a></li>
		<li id="modification" class="active"><a href="/edit/mods/">Modifications</a></li>
		<li id="ownership"><a href="/edit/owner/">Ownership</a></li>
		<li id="documents"><a href="/edit/documents/">Documents</a></li>
		<li id="photos"><a href="/edit/photos/">Photos</a></li>
	</ul>
</div> <!-- /#vehicle-edit-nav -->
<!-- /#vehicle-edit-nav -->
<div id="vehicle-edit-form">  
						<form id="ownership_form" method="POST" action="/vehicles/demo/1959-chevrolet-bel-air-1/edit/ownership/">
							<div style='display:none'><input type='hidden' name='csrfmiddlewaretoken' value='cfcb199b35cd013c5683651dab41a9be' /></div>
							<fieldset id="ownership_history">
								<legend><span>Ownership History</span></legend>
		
								<div class="form-content-wrapper clearfix">
									<p class="form-wide-help">Enter the date and location when purchased</p>
									<div class="ownership">
										<label for="id_own_purchase_date">Purchase Date</label>
										<span class="form-field">
											<input type="text" name="own_purchase_date" id="id_own_purchase_date" />
										</span>
									</div>
									<div class="ownership">
										<label for="id_own_purchase_city">City</label>
										<span class="form-field">
											<input id="id_own_purchase_city" type="text" name="own_purchase_city" maxlength="25" />
										</span>
									</div>
									
									<div class="ownership">
										<label for="id_own_purchase_state">State</label>
										<span class="form-field">
											<select id="id_own_purchase_state" style="width:228px" data-placeholder="Choose a state" class="chzn-select" name="own_purchase_state">
												<option value="" selected="selected"></option>
												<option value="AL">Alabama</option>
												<option value="AK">Alaska</option>
												<option value="AS">American Samoa</option>
												<option value="AZ">Arizona</option>
												<option value="AR">Arkansas</option>
												<option value="AA">Armed Forces Americas</option>
												<option value="AE">Armed Forces Europe</option>
												<option value="AP">Armed Forces Pacific</option>
												<option value="CA">California</option>
												<option value="CO">Colorado</option>
												<option value="CT">Connecticut</option>
												<option value="DE">Delaware</option>
												<option value="DC">District of Columbia</option>
												<option value="FL">Florida</option>
												<option value="GA">Georgia</option>
												<option value="GU">Guam</option>
												<option value="HI">Hawaii</option>
												<option value="ID">Idaho</option>
												<option value="IL">Illinois</option>
												<option value="IN">Indiana</option>
												<option value="IA">Iowa</option>
												<option value="KS">Kansas</option>
												<option value="KY">Kentucky</option>
												<option value="LA">Louisiana</option>
												<option value="ME">Maine</option>
												<option value="MD">Maryland</option>
												<option value="MA">Massachusetts</option>
												<option value="MI">Michigan</option>
												<option value="MN">Minnesota</option>
												<option value="MS">Mississippi</option>
												<option value="MO">Missouri</option>
												<option value="MT">Montana</option>
												<option value="NE">Nebraska</option>
												<option value="NV">Nevada</option>
												<option value="NH">New Hampshire</option>
												<option value="NJ">New Jersey</option>
												<option value="NM">New Mexico</option>
												<option value="NY">New York</option>
												<option value="NC">North Carolina</option>
												<option value="ND">North Dakota</option>
												<option value="MP">Northern Mariana Islands</option>
												<option value="OH">Ohio</option>
												<option value="OK">Oklahoma</option>
												<option value="OR">Oregon</option>
												<option value="PA">Pennsylvania</option>
												<option value="PR">Puerto Rico</option>
												<option value="RI">Rhode Island</option>
												<option value="SC">South Carolina</option>
												<option value="SD">South Dakota</option>
												<option value="TN">Tennessee</option>
												<option value="TX">Texas</option>
												<option value="UT">Utah</option>
												<option value="VT">Vermont</option>
												<option value="VI">Virgin Islands</option>
												<option value="VA">Virginia</option>
												<option value="WA">Washington</option>
												<option value="WV">West Virginia</option>
												<option value="WI">Wisconsin</option>
												<option value="WY">Wyoming</option>
											</select>
										</span>
									</div>
									
									<div class="ownership">
										<label for="id_own_owner">Actual Owner</label>
										<span class="form-field">
											<select id="id_own_owner" style="width:228px" data-placeholder="Select an Option..." class="chzn-select" name="own_owner">
												<option value=""></option>
												<option value="Self" selected="selected">Self</option>
												<option value="Father">Father</option>
												<option value="Mother">Mother</option>
												<option value="Brother">Brother</option>
												<option value="Sister">Sister</option>
												<option value="Grandfather">Grandfather</option>
												<option value="Grandmother">Grandmother</option>
												<option value="Uncle">Uncle</option>
												<option value="Aunt">Aunt</option>
												<option value="Cousin">Cousin</option>
												<option value="Friend">Friend</option>
												<option value="other">other</option>
											</select>
										</span>
										<br class="clear" />
										<label for="id_own_owner_other">&nbsp;</label>
										<span id="id_own_owner_other" class="form-field other">
											<input id="id_own_owner_other" type="text" name="own_owner_other" maxlength="25" />
										</span>
									</div>
									
									<p class="form-wide-help clear">If you sell your classic after creating a 
									Garagistry record, enter the date and location when sold.
									</p>
									
									<div class="ownership">
										<label for="id_own_sold_date">Sold Date</label>
										<span class="form-field">
											<input type="text" name="own_sold_date" id="id_own_sold_date" />
										</span>
									</div>
									
									<div class="ownership">
										<label for="id_own_sold_city">City</label>
										<span class="form-field">
											<input id="id_own_sold_city" type="text" name="own_sold_city" maxlength="25" />
										</span>
									</div>
									
									<div class="ownership">
										<label for="id_own_sold_state">State</label>
										<span class="form-field">
											<select id="id_own_sold_state" style="width:228px" data-placeholder="Choose a state" class="chzn-select" name="own_sold_state">
												<option value="" selected="selected"></option>
												<option value="AL">Alabama</option>
												<option value="AK">Alaska</option>
												<option value="AS">American Samoa</option>
												<option value="AZ">Arizona</option>
												<option value="AR">Arkansas</option>
												<option value="AA">Armed Forces Americas</option>
												<option value="AE">Armed Forces Europe</option>
												<option value="AP">Armed Forces Pacific</option>
												<option value="CA">California</option>
												<option value="CO">Colorado</option>
												<option value="CT">Connecticut</option>
												<option value="DE">Delaware</option>
												<option value="DC">District of Columbia</option>
												<option value="FL">Florida</option>
												<option value="GA">Georgia</option>
												<option value="GU">Guam</option>
												<option value="HI">Hawaii</option>
												<option value="ID">Idaho</option>
												<option value="IL">Illinois</option>
												<option value="IN">Indiana</option>
												<option value="IA">Iowa</option>
												<option value="KS">Kansas</option>
												<option value="KY">Kentucky</option>
												<option value="LA">Louisiana</option>
												<option value="ME">Maine</option>
												<option value="MD">Maryland</option>
												<option value="MA">Massachusetts</option>
												<option value="MI">Michigan</option>
												<option value="MN">Minnesota</option>
												<option value="MS">Mississippi</option>
												<option value="MO">Missouri</option>
												<option value="MT">Montana</option>
												<option value="NE">Nebraska</option>
												<option value="NV">Nevada</option>
												<option value="NH">New Hampshire</option>
												<option value="NJ">New Jersey</option>
												<option value="NM">New Mexico</option>
												<option value="NY">New York</option>
												<option value="NC">North Carolina</option>
												<option value="ND">North Dakota</option>
												<option value="MP">Northern Mariana Islands</option>
												<option value="OH">Ohio</option>
												<option value="OK">Oklahoma</option>
												<option value="OR">Oregon</option>
												<option value="PA">Pennsylvania</option>
												<option value="PR">Puerto Rico</option>
												<option value="RI">Rhode Island</option>
												<option value="SC">South Carolina</option>
												<option value="SD">South Dakota</option>
												<option value="TN">Tennessee</option>
												<option value="TX">Texas</option>
												<option value="UT">Utah</option>
												<option value="VT">Vermont</option>
												<option value="VI">Virgin Islands</option>
												<option value="VA">Virginia</option>
												<option value="WA">Washington</option>
												<option value="WV">West Virginia</option>
												<option value="WI">Wisconsin</option>
												<option value="WY">Wyoming</option>
											</select>
										</span>
									</div>
									<p class="form-wide-help clear">Use this section if you have undocumented information about your classic and it's history, especially if it is not recorded within the available 
									<a href="/vehicles/demo/1959-chevrolet-bel-air-1/edit/documents/">vehicle documents</a>
									in your possession.
									</p>
									<div class="ownership">
										<label for="id_own_details">Additional Details</label>
										<span class="form-field">
											<textarea id="id_own_details" rows="10" cols="40" name="own_details"></textarea>
										</span>
									</div>
								</div>
							</fieldset>
							<input type="submit" value="Save Changes" class="button" />
						</form>
					
					</div> <!-- /#vehicle-edit-form -->
