<div id="vehicle-edit-head" class="vehicle">
<div id="vehicle-rvt">
	<img src="/images/rvt_sample-100.png" width="100" height="57" />
</div>
<div class="vehicle-photo">
	<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air2_profile.jpg" alt="The Bel Air" title="" />
</div>
<div id="vehicle-title">
	<div id="vehicle-year">1959</div>
	<div id="vehicle-make">Chevrolet</div>
	<div id="vehicle-model">Bel Air</div>
</div>
<div class="profile-completion">
	<span class="completion-percentage">NEEDED: transmission type, transmission speeds...</span> PROFILE COMPLETION: 35%
	<div class="completion-bar"><span style="width: 35%"></span></div>
</div>
<!-- /.profile-completion -->
</div>
<div id="vehicle-edit-nav">
	<ul>
		<li id="specs"><a href="/edit">Vehicle Specs</a></li>
		<li id="trim"><a href="/edit/trim/">Trim Level</a></li>
		<li id="modification" class=""><a href="/edit/mods/">Modifications</a></li>
		<li id="ownership"><a href="/edit/owner/">Ownership</a></li>
		<li id="documents" ><a href="/edit/documents/">Documents</a></li>
		<li id="photos" class="active"><a href="/edit/photos/">Photos</a></li>
	</ul>
</div> <!-- /#vehicle-edit-nav -->
<!-- /#vehicle-edit-nav -->
<div id="vehicle-edit-form">
	<h1>My Photos</h1>
	<p class="photo-count">33 Photos</p>
	<a class="add-photo" href="/edit/addphoto">Add Photos</a>		
	<div id="photos" class="clearfix">
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/0713080136_thumb.jpg" alt="Test Taggggg" title="Super public trim tag" />
			</a>
			<p class="title">Test Taggggg</p>
			<p class="caption">Super public trim&#8230;</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air1_thumb.jpg" alt="By the tree..." title="" />
			</a>
			<p class="title">By the tree…</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
			<a class="reference" href="http://en.wikipedia.org/wiki/Burrowing_Owl" rel="reference.html">Reference</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air3_thumb.jpg" alt="Another view" title="" />
			</a>
			<p class="title">Another view</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air2_thumb.jpg" alt="The Bel Air" title="" />
			</a>
			<p class="title">The Bel Air</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
			<a class="reference" href="http://en.wikipedia.org/wiki/Burrowing_Owl" rel="reference.html">Reference</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air4_thumb.jpg" alt="My favorite" title="" />
			</a>
			<p class="title">My favorite</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/0713080136_thumb.jpg" alt="Test Taggggg" title="Super public trim tag" />
			</a>
			<p class="title">Test Taggggg</p>
			<p class="caption">Super public trim&#8230;</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air1_thumb.jpg" alt="By the tree..." title="" />
			</a>
			<p class="title">By the tree…</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
			<a class="reference" href="http://en.wikipedia.org/wiki/Burrowing_Owl" rel="reference.html">Reference</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air3_thumb.jpg" alt="Another view" title="" />
			</a>
			<p class="title">Another view</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air2_thumb.jpg" alt="The Bel Air" title="" />
			</a>
			<p class="title">The Bel Air</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
			<a class="reference" href="http://en.wikipedia.org/wiki/Burrowing_Owl" rel="reference.html">Reference</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air4_thumb.jpg" alt="My favorite" title="" />
			</a>
			<p class="title">My favorite</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air3_thumb.jpg" alt="Another view" title="" />
			</a>
			<p class="title">Another view</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
		</div>
		<div class="photo-edit-thumb">
			<a href="view-photo.html" class="photo-link">
			<img src="/media/photo_cache/demo/__1957-chevrolet-bel-air2_thumb.jpg" alt="The Bel Air" title="" />
			</a>
			<p class="title">The Bel Air</p>
			<a class="edit" href="/edit/editphoto">Edit</a>
			<a class="reference" href="http://en.wikipedia.org/wiki/Burrowing_Owl" rel="reference.html">Reference</a>
		</div>
		<div id="photo-navigation">
			<a class="prev" href="#">Previous</a>
			<div class="pagination">
				<span class="current page">1</span>
				<a class="page" href="#">2</a>
				<a class="page" href="#">3</a>
			</div>
			<a class="next" href="#">Next</a>
		</div>
		<!-- /#photo-navigation -->
	</div>
	<!-- /#photos -->
</div>
<!-- /#vehicle-edit-form -->	