<div id="vehicle-edit-head" class="vehicle">
   <div id="vehicle-rvt">
      <img src="/images/rvt_sample-100.png" width="100" height="57" />
   </div>
   <div class="vehicle-photo">
      <img src="/media/photo_cache/demo/__1957-chevrolet-bel-air2_profile.jpg" alt="The Bel Air" title="" />
   </div>
   <div id="vehicle-title">
      <div id="vehicle-year">1959</div>
      <div id="vehicle-make">Chevrolet</div>
      <div id="vehicle-model">Bel Air</div>
   </div>
   <div class="profile-completion">
      <span class="completion-percentage">NEEDED: transmission type, transmission speeds...</span>
      PROFILE COMPLETION: 35%
      <div class="completion-bar"><span style="width: 35%"></span></div>
   </div>
   <!-- /.profile-completion -->
</div>
<div id="vehicle-edit-nav">
	<ul>
		<li id="specs" ><a href="/edit">Vehicle Specs</a></li>
		<li id="trim" class="active"><a href="/edit/trim/">Trim Level</a></li>
		<li id="modification" class=""><a href="/edit/mods/">Modifications</a></li>
		<li id="ownership"><a href="/edit/owner/">Ownership</a></li>
		<li id="documents" class=""><a href="/edit/documents/">Documents</a></li>
		<li id="photos" class=""><a href="/edit/photos/">Photos</a></li>
	</ul>
</div>
<!-- /#vehicle-edit-nav -->
<div id="vehicle-edit-form">  
	<form id="vehicle_trim" method="POST" enctype="multipart/form-data" action="/vehicles/demo/1959-chevrolet-bel-air-1/edit/trim/">
		<div style='display:none'>
			<input type='hidden' name='csrfmiddlewaretoken' value='cfcb199b35cd013c5683651dab41a9be' />
		</div>
		<fieldset id="vehicle_trim_photo">
			<legend><span>My Trim Photo</span></legend>
			<div class="form-content-wrapper">
				<div id="id_vehicle_trim_titles">
					<div id="tag_main">
						<a class="select-tag" href="/edit/addtag">Select a Photo</a>
						<p><strong>You can upload JPG, GIF or PNG files less than 1MB in size.</strong></p>
						<p>By uploading this file you declare that you have the right to distribute this file and that it does not violate the <a href="#">User Agreement</a>.</p>
					</div>
					<div id="example-tags">
						<p>Example Trim Tags</p>
						<a href="/media/document_cache/demo/example-tag1.png" class="example-tag"><img src="/media/document_cache/demo/example-tag-thumb1.png" /><img class="zoom" src="/images/icons/zoom.png" /></a>
						<a href="/media/document_cache/demo/example-tag2.png" class="example-tag"><img src="/media/document_cache/demo/example-tag-thumb2.png" /><img class="zoom" src="/images/icons/zoom.png" /></a>
					</div>
				</div>
			</div>
		</fieldset>
		<fieldset id="id_vehicle_trim_codes">
			<legend><span>Trim Tag Codes</span></legend>
			<div class="form-content-wrapper">
				<div class="trimtag">
					<label for="id_tt_country_origin">Country of Origin</label>
					<span>
						<span class="form-field">
							<select id="id_tt_country_origin" data-placeholder="Choose a Country" class=" chzn-select" name="tt_country_origin">
								<option value="" selected="selected"></option>
								<option value="US">United States of America</option>
								<option value="AF">Afghanistan</option>
								<option value="AX">Aland</option>
								<option value="AL">Albania</option>
								<option value="DZ">Algeria</option>
								<option value="AS">American Samoa</option>
								<option value="AD">Andorra</option>
								<option value="AO">Angola</option>
								<option value="AI">Anguilla</option>
								<option value="AQ">Antarctica</option>
								<option value="AG">Antigua and Barbuda</option>
								<option value="AR">Argentina</option>
								<option value="AM">Armenia</option>
								<option value="AW">Aruba</option>
								<option value="AU">Australia</option>
								<option value="AT">Austria</option>
								<option value="AZ">Azerbaijan</option>
								<option value="BS">Bahamas</option>
								<option value="BH">Bahrain</option>
								<option value="BD">Bangladesh</option>
								<option value="BB">Barbados</option>
								<option value="BY">Belarus</option>
								<option value="BE">Belgium</option>
								<option value="BZ">Belize</option>
								<option value="BJ">Benin</option>
								<option value="BM">Bermuda</option>
								<option value="BT">Bhutan</option>
								<option value="BO">Bolivia</option>
								<option value="BA">Bosnia and Herzegovina</option>
								<option value="BW">Botswana</option>
								<option value="BV">Bouvet Island</option>
								<option value="BR">Brazil</option>
								<option value="IO">British Indian Ocean Territory</option>
								<option value="BN">Brunei Darussalam</option>
								<option value="BG">Bulgaria</option>
								<option value="BF">Burkina Faso</option>
								<option value="BI">Burundi</option>
								<option value="KH">Cambodia</option>
								<option value="CM">Cameroon</option>
								<option value="CA">Canada</option>
								<option value="CV">Cape Verde</option>
								<option value="KY">Cayman Islands</option>
								<option value="CF">Central African Republic</option>
								<option value="TD">Chad</option>
								<option value="CL">Chile</option>
								<option value="CN">China</option>
								<option value="CX">Christmas Island</option>
								<option value="CC">Cocos (Keeling) Islands</option>
								<option value="CO">Colombia</option>
								<option value="KM">Comoros</option>
								<option value="CG">Congo (Brazzaville)</option>
								<option value="CD">Congo (Kinshasa)</option>
								<option value="CK">Cook Islands</option>
								<option value="CR">Costa Rica</option>
								<option value="CI">Cote d&#39;Ivoire</option>
								<option value="HR">Croatia</option>
								<option value="CU">Cuba</option>
								<option value="CY">Cyprus</option>
								<option value="CZ">Czech Republic</option>
								<option value="DK">Denmark</option>
								<option value="DJ">Djibouti</option>
								<option value="DM">Dominica</option>
								<option value="DO">Dominican Republic</option>
								<option value="EC">Ecuador</option>
								<option value="EG">Egypt</option>
								<option value="SV">El Salvador</option>
								<option value="GQ">Equatorial Guinea</option>
								<option value="ER">Eritrea</option>
								<option value="EE">Estonia</option>
								<option value="ET">Ethiopia</option>
								<option value="FK">Falkland Islands</option>
								<option value="FO">Faroe Islands</option>
								<option value="FJ">Fiji</option>
								<option value="FI">Finland</option>
								<option value="FR">France</option>
								<option value="GF">French Guiana</option>
								<option value="PF">French Polynesia</option>
								<option value="TF">French Southern Lands</option>
								<option value="GA">Gabon</option>
								<option value="GM">Gambia</option>
								<option value="GE">Georgia</option>
								<option value="DE">Germany</option>
								<option value="GH">Ghana</option>
								<option value="GI">Gibraltar</option>
								<option value="GR">Greece</option>
								<option value="GL">Greenland</option>
								<option value="GD">Grenada</option>
								<option value="GP">Guadeloupe</option>
								<option value="GU">Guam</option>
								<option value="GT">Guatemala</option>
								<option value="GG">Guernsey</option>
								<option value="GN">Guinea</option>
								<option value="GW">Guinea-Bissau</option>
								<option value="GY">Guyana</option>
								<option value="HT">Haiti</option>
								<option value="HM">Heard and McDonald Islands</option>
								<option value="HN">Honduras</option>
								<option value="HK">Hong Kong</option>
								<option value="HU">Hungary</option>
								<option value="IS">Iceland</option>
								<option value="IN">India</option>
								<option value="ID">Indonesia</option>
								<option value="IR">Iran</option>
								<option value="IQ">Iraq</option>
								<option value="IE">Ireland</option>
								<option value="IM">Isle of Man</option>
								<option value="IL">Israel</option>
								<option value="IT">Italy</option>
								<option value="JM">Jamaica</option>
								<option value="JP">Japan</option>
								<option value="JE">Jersey</option>
								<option value="JO">Jordan</option>
								<option value="KZ">Kazakhstan</option>
								<option value="KE">Kenya</option>
								<option value="KI">Kiribati</option>
								<option value="KP">Korea, North</option>
								<option value="KR">Korea, South</option>
								<option value="KW">Kuwait</option>
								<option value="KG">Kyrgyzstan</option>
								<option value="LA">Laos</option>
								<option value="LV">Latvia</option>
								<option value="LB">Lebanon</option>
								<option value="LS">Lesotho</option>
								<option value="LR">Liberia</option>
								<option value="LY">Libya</option>
								<option value="LI">Liechtenstein</option>
								<option value="LT">Lithuania</option>
								<option value="LU">Luxembourg</option>
								<option value="MO">Macau</option>
								<option value="MK">Macedonia</option>
								<option value="MG">Madagascar</option>
								<option value="MW">Malawi</option>
								<option value="MY">Malaysia</option>
								<option value="MV">Maldives</option>
								<option value="ML">Mali</option>
								<option value="MT">Malta</option>
								<option value="MH">Marshall Islands</option>
								<option value="MQ">Martinique</option>
								<option value="MR">Mauritania</option>
								<option value="MU">Mauritius</option>
								<option value="YT">Mayotte</option>
								<option value="MX">Mexico</option>
								<option value="FM">Micronesia</option>
								<option value="MD">Moldova</option>
								<option value="MC">Monaco</option>
								<option value="MN">Mongolia</option>
								<option value="ME">Montenegro</option>
								<option value="MS">Montserrat</option>
								<option value="MA">Morocco</option>
								<option value="MZ">Mozambique</option>
								<option value="MM">Myanmar</option>
								<option value="NA">Namibia</option>
								<option value="NR">Nauru</option>
								<option value="NP">Nepal</option>
								<option value="NL">Netherlands</option>
								<option value="AN">Netherlands Antilles</option>
								<option value="NC">New Caledonia</option>
								<option value="NZ">New Zealand</option>
								<option value="NI">Nicaragua</option>
								<option value="NE">Niger</option>
								<option value="NG">Nigeria</option>
								<option value="NU">Niue</option>
								<option value="NF">Norfolk Island</option>
								<option value="MP">Northern Mariana Islands</option>
								<option value="NO">Norway</option>
								<option value="OM">Oman</option>
								<option value="PK">Pakistan</option>
								<option value="PW">Palau</option>
								<option value="PS">Palestine</option>
								<option value="PA">Panama</option>
								<option value="PG">Papua New Guinea</option>
								<option value="PY">Paraguay</option>
								<option value="PE">Peru</option>
								<option value="PH">Philippines</option>
								<option value="PN">Pitcairn</option>
								<option value="PL">Poland</option>
								<option value="PT">Portugal</option>
								<option value="PR">Puerto Rico</option>
								<option value="QA">Qatar</option>
								<option value="RE">Reunion</option>
								<option value="RO">Romania</option>
								<option value="RU">Russian Federation</option>
								<option value="RW">Rwanda</option>
								<option value="BL">Saint Barthelemy</option>
								<option value="SH">Saint Helena</option>
								<option value="KN">Saint Kitts and Nevis</option>
								<option value="LC">Saint Lucia</option>
								<option value="MF">Saint Martin (French part)</option>
								<option value="PM">Saint Pierre and Miquelon</option>
								<option value="VC">Saint Vincent and the Grenadines</option>
								<option value="WS">Samoa</option>
								<option value="SM">San Marino</option>
								<option value="ST">Sao Tome and Principe</option>
								<option value="SA">Saudi Arabia</option>
								<option value="SN">Senegal</option>
								<option value="RS">Serbia</option>
								<option value="SC">Seychelles</option>
								<option value="SL">Sierra Leone</option>
								<option value="SG">Singapore</option>
								<option value="SK">Slovakia</option>
								<option value="SI">Slovenia</option>
								<option value="SB">Solomon Islands</option>
								<option value="SO">Somalia</option>
								<option value="ZA">South Africa</option>
								<option value="GS">South Georgia and South Sandwich Islands</option>
								<option value="ES">Spain</option>
								<option value="LK">Sri Lanka</option>
								<option value="SD">Sudan</option>
								<option value="SR">Suriname</option>
								<option value="SJ">Svalbard and Jan Mayen Islands</option>
								<option value="SZ">Swaziland</option>
								<option value="SE">Sweden</option>
								<option value="CH">Switzerland</option>
								<option value="SY">Syria</option>
								<option value="TW">Taiwan</option>
								<option value="TJ">Tajikistan</option>
								<option value="TZ">Tanzania</option>
								<option value="TH">Thailand</option>
								<option value="TL">Timor-Leste</option>
								<option value="TG">Togo</option>
								<option value="TK">Tokelau</option>
								<option value="TO">Tonga</option>
								<option value="TT">Trinidad and Tobago</option>
								<option value="TN">Tunisia</option>
								<option value="TR">Turkey</option>
								<option value="TM">Turkmenistan</option>
								<option value="TC">Turks and Caicos Islands</option>
								<option value="TV">Tuvalu</option>
								<option value="UG">Uganda</option>
								<option value="UA">Ukraine</option>
								<option value="AE">United Arab Emirates</option>
								<option value="GB">United Kingdom</option>
								<option value="UM">United States Minor Outlying Islands</option>
								<option value="UY">Uruguay</option>
								<option value="UZ">Uzbekistan</option>
								<option value="VU">Vanuatu</option>
								<option value="VA">Vatican City</option>
								<option value="VE">Venezuela</option>
								<option value="VN">Vietnam</option>
								<option value="VG">Virgin Islands, British</option>
								<option value="VI">Virgin Islands, U.S.</option>
								<option value="WF">Wallis and Futuna Islands</option>
								<option value="EH">Western Sahara</option>
								<option value="YE">Yemen</option>
								<option value="ZM">Zambia</option>
								<option value="ZW">Zimbabwe</option>
							</select>
						</span>
					</span>
				</div>
				<div class="trimtag">
					<label for="id_tt_build_date">Build Date</label>
					<span>
						<span class="form-field"><input style="width: 118px;" type="text" name="tt_build_date" id="id_tt_build_date" /></span>
					</span>
				</div>
				<div class="trimtag">
					<label for="id_tt_model_year">Model Year</label>
					<span>
						<span class="form-field">
							<select id="id_tt_model_year"  data-placeholder=" ..." class="chzn-select" name="tt_model_year">
								<option value=""></option>
								<option value=""></option>
								<option value="1986">1986</option>
								<option value="1985">1985</option>
								<option value="1984">1984</option>
								<option value="1983">1983</option>
								<option value="1982">1982</option>
								<option value="1981">1981</option>
								<option value="1980">1980</option>
								<option value="1979">1979</option>
								<option value="1978">1978</option>
								<option value="1977">1977</option>
								<option value="1976">1976</option>
								<option value="1975">1975</option>
								<option value="1974">1974</option>
								<option value="1973">1973</option>
								<option value="1972">1972</option>
								<option value="1971">1971</option>
								<option value="1970">1970</option>
								<option value="1969">1969</option>
								<option value="1968">1968</option>
								<option value="1967">1967</option>
								<option value="1966">1966</option>
								<option value="1965">1965</option>
								<option value="1964">1964</option>
								<option value="1963">1963</option>
								<option value="1962">1962</option>
								<option value="1961">1961</option>
								<option value="1960">1960</option>
								<option value="1959" selected="selected">1959</option>
								<option value="1958">1958</option>
								<option value="1957">1957</option>
								<option value="1956">1956</option>
								<option value="1955">1955</option>
								<option value="1954">1954</option>
								<option value="1953">1953</option>
								<option value="1952">1952</option>
								<option value="1951">1951</option>
								<option value="1950">1950</option>
								<option value="1949">1949</option>
								<option value="1948">1948</option>
								<option value="1947">1947</option>
								<option value="1946">1946</option>
								<option value="1945">1945</option>
								<option value="1944">1944</option>
								<option value="1943">1943</option>
								<option value="1942">1942</option>
								<option value="1941">1941</option>
								<option value="1940">1940</option>
								<option value="1939">1939</option>
								<option value="1938">1938</option>
								<option value="1937">1937</option>
								<option value="1936">1936</option>
								<option value="1935">1935</option>
								<option value="1934">1934</option>
								<option value="1933">1933</option>
								<option value="1932">1932</option>
								<option value="1931">1931</option>
								<option value="1930">1930</option>
								<option value="1929">1929</option>
								<option value="1928">1928</option>
								<option value="1927">1927</option>
								<option value="1926">1926</option>
								<option value="1925">1925</option>
								<option value="1924">1924</option>
								<option value="1923">1923</option>
								<option value="1922">1922</option>
								<option value="1921">1921</option>
								<option value="1920">1920</option>
								<option value="1919">1919</option>
								<option value="1918">1918</option>
								<option value="1917">1917</option>
								<option value="1916">1916</option>
								<option value="1915">1915</option>
								<option value="1914">1914</option>
								<option value="1913">1913</option>
								<option value="1912">1912</option>
								<option value="1911">1911</option>
								<option value="1910">1910</option>
								<option value="1909">1909</option>
								<option value="1908">1908</option>
								<option value="1907">1907</option>
								<option value="1906">1906</option>
								<option value="1905">1905</option>
								<option value="1904">1904</option>
								<option value="1903">1903</option>
								<option value="1902">1902</option>
								<option value="1901">1901</option>
								<option value="1900">1900</option>
								<option value="1899">1899</option>
								<option value="1898">1898</option>
								<option value="1897">1897</option>
							</select>
						</span>
						
					</span>
				</div>
				
				<div class="trimtag">
					<label for="id_tt_unit_number">Chassis/Unit Number</label>
					<span>
						<span class="form-field"><input id="id_tt_unit_number" type="text" name="tt_unit_number" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div class="trimtag">
					<label for="id_tt_body_type">Vehicle/Body Code</label>
					<span>
						<span class="form-field"><input id="id_tt_body_type" type="text" name="tt_body_type" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div class="trimtag">
					<label for="id_tt_model_code">Model Code</label>
					<span>
						<span class="form-field"><input id="id_tt_model_code" type="text" name="tt_model_code" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div class="trimtag">
					<label for="id_tt_ext_color">Paint/exterior Color</label>
					<span>
						<span class="form-field"><input id="id_tt_ext_color" type="text" name="tt_ext_color" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div class="trimtag">
					<label for="id_tt_trim_number">Trim Level</label>
					<span>
						<span class="form-field"><input id="id_tt_trim_number" type="text" name="tt_trim_number" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div class="trimtag">
					<label for="id_tt_int_color">Interior Color</label>
					<span>
						<span class="form-field"><input id="id_tt_int_color" type="text" name="tt_int_color" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div class="trimtag">
					<label for="id_tt_engine_code">Engine Code</label>
					<span>
						<span class="form-field"><input id="id_tt_engine_code" type="text" name="tt_engine_code" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div class="trimtag">
					<label for="id_tt_trans_code">Transmission Code</label>
					<span>
						<span class="form-field"><input id="id_tt_trans_code" type="text" name="tt_trans_code" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div class="trimtag">
					<label for="id_tt_options_code">Options Code</label>
					<span>
						<span class="form-field"><input id="id_tt_options_code" type="text" name="tt_options_code" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div id="other1" class="trimtag other">
					<span class="trimtag-label">
						<span class="form-field"><input name="tt_other_label1" maxlength="20" placeholder="Label" type="text" class="options-label" id="id_tt_other_label1" /></span>
						
					</span>
					<span class="trimtag-value">
						<span class="form-field"><input id="id_tt_other_value1" type="text" name="tt_other_value1" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div id="other2" class="trimtag other">
					<span class="trimtag-label">
						<span class="form-field"><input name="tt_other_label2" maxlength="20" placeholder="Label" type="text" class="options-label" id="id_tt_other_label2" /></span>
						
				
					</span>
					<span class="trimtag-value">
						<span class="form-field"><input id="id_tt_other_value2" type="text" name="tt_other_value2" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div id="other3" class="trimtag other">
					<span class="trimtag-label">
						<span class="form-field"><input name="tt_other_label3" maxlength="20" placeholder="Label" type="text" class="options-label" id="id_tt_other_label3" /></span>
						<br class="clear" />
					</span>
					<span class="trimtag-value">
						<span class="form-field"><input id="id_tt_other_value3" type="text" name="tt_other_value3" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div id="other4" class="trimtag other">
					<span class="trimtag-label">
						<span class="form-field"><input name="tt_other_label4" maxlength="20" placeholder="Label" type="text" class="options-label" id="id_tt_other_label4" /></span>
						
					</span>
					<span class="trimtag-value">
						<span class="form-field"><input id="id_tt_other_value4" type="text" name="tt_other_value4" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div id="other5" class="trimtag other">
					<span class="trimtag-label">
						<span class="form-field"><input name="tt_other_label5" maxlength="20" placeholder="Label" type="text" class="options-label" id="id_tt_other_label5" /></span>
						
					</span>
					<span class="trimtag-value">
						<span class="form-field"><input id="id_tt_other_value5" type="text" name="tt_other_value5" maxlength="20" /></span>
						
					</span>
				</div>
				
				<div id="add-code" class="trimtag">
					
					<span class="trimtag-value">
						<a onclick="showNextOtherCode()">
							<span class="add-code">
								Add another code
							</span>
						</a>
					</span>
				</div>
			
			</div><!-- /#form-content-wrapper -->
			
			<div id="vehicle_trim_help" class="vehicle-trim-help">
				<p><strong>Enter codes exactly as they appear on your Trim Tag.</strong></p>
				<p>Are we missing any fields from your tag? You may create your own or <a href="/about/contact/">let us know</a> what's missing.</p>
			</div>
		
		</fieldset>
		<input type="submit" value="Save Changes" class="button" />
	</form>

</div> <!-- /#vehicle-edit-form -->